repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-toml
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
        args: [--branch, main]
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
    -   id: ruff-format
    -   id: ruff
        args: [--fix, --exit-zero]
        pass_filenames: true
        always_run: true
        verbose: true